controller_joint_names: [L_HipYaw, L_HipRoll, L_HipPitch, L_KneePitch, L_AnklePitch, L_AnkleRoll, R_HipYaw,
  R_HipRoll, R_HipPitch, R_KneePitch, R_AnklePitch, R_AnkleRoll, WaistPitch, WaistYaw,
  L_ShoulderPitch, L_ShoulderRoll, L_ShoulderYaw, L_ElbowRoll, L_WristYaw, L_WristRoll,
  L_HandYaw, R_ShoulderPitch, R_ShoulderRoll, R_ShoulderYaw, R_ElbowRoll, R_WristYaw,
  R_WristRoll, R_HandYaw]
